version: '3.7'

services:

  redis:
    image: redis:alpine
    networks:
      - redis
    volumes:
      - redis:/data

  redis-backup:
    image: redis-backup
    command: /redis-backup.sh
    networks:
      - redis
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      REDIS_HOST: "redis"
    volumes:
      - redis:/data:ro
      - /backups/redis:/redisbackup:rw
    depends_on:
      - redis

volumes:
  redis:

networks:
  redis:
